source "https://rubygems.org"

gem "sinatra"
gem "datamapper"

group :development do
  gem "sqlite3"
  gem "dm-sqlite-adapter"
  gem "dotenv"
  gem "rerun"
end

group :production do
  gem "pg"
  gem "dm-postgres-adapter"
end
