source 'https://rubygems.org'

ruby '2.1.3'

gem 'sinatra'
gem 'data_mapper'

group :production do
  gem 'pg'
  gem 'dm-postgres-adapter'
end

group :development do
  gem 'sqlite3'
  gem 'dm-sqlite-adapter'
end
